// <auto-generated />
using FitAppReact.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FitAppReact.EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210830112124_SeedUpdate")]
    partial class SeedUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.Hazard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hazards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High amounts of sugar",
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Presence of lactose",
                            Name = "Lactose"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Presence of nuts",
                            Name = "Nuts"
                        });
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MealCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recipe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MealCategoryId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description of breakfast 1",
                            MealCategoryId = 1,
                            Name = "Breakfast 1",
                            Recipe = "Recipe of breakfast 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description of breakfast 2",
                            MealCategoryId = 1,
                            Name = "Breakfast 2",
                            Recipe = "Recipe of breakfast 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description of breakfast 3",
                            MealCategoryId = 1,
                            Name = "Breakfast 3",
                            Recipe = "Recipe of breakfast 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description of breakfast 4",
                            MealCategoryId = 1,
                            Name = "Breakfast 4",
                            Recipe = "Recipe of breakfast 4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description of breakfast 5",
                            MealCategoryId = 1,
                            Name = "Breakfast 5",
                            Recipe = "Recipe of breakfast 5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description of dinner 1",
                            MealCategoryId = 1,
                            Name = "Dinner 1",
                            Recipe = "Recipe of dinner 1"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description of dinner 2",
                            MealCategoryId = 1,
                            Name = "Dinner 2",
                            Recipe = "Recipe of dinner 2"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description of dinner 3",
                            MealCategoryId = 1,
                            Name = "Dinner 3",
                            Recipe = "Recipe of dinner 3"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description of dinner 4",
                            MealCategoryId = 1,
                            Name = "Dinner 4",
                            Recipe = "Recipe of dinner 4"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description of dinner 5",
                            MealCategoryId = 1,
                            Name = "Dinner 5",
                            Recipe = "Recipe of dinner 5"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Description of lunch 1",
                            MealCategoryId = 2,
                            Name = "Lunch 1",
                            Recipe = "Recipe of lunch 1"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Description of lunch 2",
                            MealCategoryId = 2,
                            Name = "Lunch 2",
                            Recipe = "Recipe of lunch 2"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Description of lunch 3",
                            MealCategoryId = 2,
                            Name = "Lunch 3",
                            Recipe = "Recipe of lunch 3"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Description of lunch 4",
                            MealCategoryId = 2,
                            Name = "Lunch 4",
                            Recipe = "Recipe of lunch 4"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Description of lunch 5",
                            MealCategoryId = 2,
                            Name = "Lunch 5",
                            Recipe = "Recipe of lunch 5"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Description of snack 1",
                            MealCategoryId = 3,
                            Name = "Snack 1",
                            Recipe = "Recipe of snack 1"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Description of snack 2",
                            MealCategoryId = 3,
                            Name = "Snack 2",
                            Recipe = "Recipe of snack 2"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Description of snack 3",
                            MealCategoryId = 3,
                            Name = "Snack 3",
                            Recipe = "Recipe of snack 3"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Description of snack 4",
                            MealCategoryId = 3,
                            Name = "Snack 4",
                            Recipe = "Recipe of snack 4"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Description of snack 5",
                            MealCategoryId = 3,
                            Name = "Snack 5",
                            Recipe = "Recipe of snack 5"
                        });
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.MealCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MealCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Breakfast/Dinner"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lunch"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Snack"
                        });
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.MealProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("ProductId");

                    b.ToTable("MealProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MealId = 1,
                            ProductId = 4,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 2,
                            MealId = 1,
                            ProductId = 28,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 3,
                            MealId = 1,
                            ProductId = 4,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 4,
                            MealId = 2,
                            ProductId = 30,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 5,
                            MealId = 2,
                            ProductId = 24,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 6,
                            MealId = 2,
                            ProductId = 7,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 7,
                            MealId = 3,
                            ProductId = 15,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 8,
                            MealId = 3,
                            ProductId = 30,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 9,
                            MealId = 3,
                            ProductId = 35,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 10,
                            MealId = 4,
                            ProductId = 12,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 11,
                            MealId = 4,
                            ProductId = 30,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 12,
                            MealId = 4,
                            ProductId = 9,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 13,
                            MealId = 5,
                            ProductId = 17,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 14,
                            MealId = 5,
                            ProductId = 14,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 15,
                            MealId = 5,
                            ProductId = 28,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 16,
                            MealId = 6,
                            ProductId = 23,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 17,
                            MealId = 6,
                            ProductId = 12,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 18,
                            MealId = 6,
                            ProductId = 24,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 19,
                            MealId = 7,
                            ProductId = 4,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 20,
                            MealId = 7,
                            ProductId = 8,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 21,
                            MealId = 7,
                            ProductId = 26,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 22,
                            MealId = 8,
                            ProductId = 9,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 23,
                            MealId = 8,
                            ProductId = 18,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 24,
                            MealId = 8,
                            ProductId = 6,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 25,
                            MealId = 9,
                            ProductId = 31,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 26,
                            MealId = 9,
                            ProductId = 20,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 27,
                            MealId = 9,
                            ProductId = 31,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 28,
                            MealId = 10,
                            ProductId = 29,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 29,
                            MealId = 10,
                            ProductId = 5,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 30,
                            MealId = 10,
                            ProductId = 15,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 31,
                            MealId = 11,
                            ProductId = 20,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 32,
                            MealId = 11,
                            ProductId = 37,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 33,
                            MealId = 11,
                            ProductId = 29,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 34,
                            MealId = 12,
                            ProductId = 5,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 35,
                            MealId = 12,
                            ProductId = 19,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 36,
                            MealId = 12,
                            ProductId = 33,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 37,
                            MealId = 13,
                            ProductId = 28,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 38,
                            MealId = 13,
                            ProductId = 17,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 39,
                            MealId = 13,
                            ProductId = 5,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 40,
                            MealId = 14,
                            ProductId = 9,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 41,
                            MealId = 14,
                            ProductId = 4,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 42,
                            MealId = 14,
                            ProductId = 15,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 43,
                            MealId = 15,
                            ProductId = 7,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 44,
                            MealId = 15,
                            ProductId = 23,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 45,
                            MealId = 15,
                            ProductId = 18,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 46,
                            MealId = 16,
                            ProductId = 5,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 47,
                            MealId = 16,
                            ProductId = 10,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 48,
                            MealId = 16,
                            ProductId = 21,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 49,
                            MealId = 17,
                            ProductId = 36,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 50,
                            MealId = 17,
                            ProductId = 36,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 51,
                            MealId = 17,
                            ProductId = 6,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 52,
                            MealId = 18,
                            ProductId = 29,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 53,
                            MealId = 18,
                            ProductId = 37,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 54,
                            MealId = 18,
                            ProductId = 8,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 55,
                            MealId = 19,
                            ProductId = 30,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 56,
                            MealId = 19,
                            ProductId = 25,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 57,
                            MealId = 19,
                            ProductId = 30,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 58,
                            MealId = 20,
                            ProductId = 28,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 59,
                            MealId = 20,
                            ProductId = 8,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 60,
                            MealId = 20,
                            ProductId = 28,
                            Quantity = 1m
                        });
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.MedicalCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedicalConditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Avoid sugars",
                            Name = "Diabetes"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Avoid lactose",
                            Name = "Lactose intolerance"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Avoid nuts",
                            Name = "Nut allergy"
                        });
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.MedicalConditionHazard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HazardId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalConditionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HazardId");

                    b.HasIndex("MedicalConditionId");

                    b.ToTable("MedicalConditionHazards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HazardId = 1,
                            MedicalConditionId = 1
                        },
                        new
                        {
                            Id = 2,
                            HazardId = 2,
                            MedicalConditionId = 2
                        },
                        new
                        {
                            Id = 3,
                            HazardId = 3,
                            MedicalConditionId = 3
                        });
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Carbohydrates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fibre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Salt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sugar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 583m,
                            Carbohydrates = 6m,
                            Fat = 52m,
                            Fibre = 11m,
                            Name = "Almond",
                            Protein = 20m,
                            Salt = 0m,
                            Sugar = 3m
                        },
                        new
                        {
                            Id = 2,
                            Calories = 54m,
                            Carbohydrates = 12m,
                            Fat = 0m,
                            Fibre = 2m,
                            Name = "Apple",
                            Protein = 0m,
                            Salt = 0m,
                            Sugar = 12m
                        },
                        new
                        {
                            Id = 3,
                            Calories = 60m,
                            Carbohydrates = 12m,
                            Fat = 0m,
                            Fibre = 2m,
                            Name = "Apricot",
                            Protein = 1m,
                            Salt = 0m,
                            Sugar = 8m
                        },
                        new
                        {
                            Id = 4,
                            Calories = 17m,
                            Carbohydrates = 1m,
                            Fat = 0m,
                            Fibre = 2m,
                            Name = "Aspargus",
                            Protein = 2m,
                            Salt = 0m,
                            Sugar = 1m
                        },
                        new
                        {
                            Id = 5,
                            Calories = 188m,
                            Carbohydrates = 2m,
                            Fat = 18m,
                            Fibre = 6m,
                            Name = "Avocado",
                            Protein = 3m,
                            Salt = 0m,
                            Sugar = 1m
                        },
                        new
                        {
                            Id = 6,
                            Calories = 86m,
                            Carbohydrates = 19m,
                            Fat = 0m,
                            Fibre = 2m,
                            Name = "Banana",
                            Protein = 1m,
                            Salt = 0m,
                            Sugar = 18m
                        },
                        new
                        {
                            Id = 7,
                            Calories = 114m,
                            Carbohydrates = 15m,
                            Fat = 1m,
                            Fibre = 11m,
                            Name = "Beans(white)",
                            Protein = 8m,
                            Salt = 0m,
                            Sugar = 0m
                        },
                        new
                        {
                            Id = 8,
                            Calories = 198m,
                            Carbohydrates = 1m,
                            Fat = 9m,
                            Fibre = 0m,
                            Name = "Beef",
                            Protein = 30m,
                            Salt = 0m,
                            Sugar = 0m
                        },
                        new
                        {
                            Id = 9,
                            Calories = 58m,
                            Carbohydrates = 9m,
                            Fat = 1m,
                            Fibre = 5m,
                            Name = "Blackberry",
                            Protein = 1m,
                            Salt = 0m,
                            Sugar = 7m
                        },
                        new
                        {
                            Id = 10,
                            Calories = 75m,
                            Carbohydrates = 15m,
                            Fat = 0m,
                            Fibre = 7m,
                            Name = "Berry",
                            Protein = 1m,
                            Salt = 0m,
                            Sugar = 14m
                        },
                        new
                        {
                            Id = 11,
                            Calories = 283m,
                            Carbohydrates = 58m,
                            Fat = 2m,
                            Fibre = 4m,
                            Name = "Bread(white)",
                            Protein = 8m,
                            Salt = 0m,
                            Sugar = 2m
                        },
                        new
                        {
                            Id = 12,
                            Calories = 262m,
                            Carbohydrates = 45m,
                            Fat = 3m,
                            Fibre = 6m,
                            Name = "Bread(whole wheat)",
                            Protein = 10m,
                            Salt = 0m,
                            Sugar = 2m
                        },
                        new
                        {
                            Id = 13,
                            Calories = 29m,
                            Carbohydrates = 2m,
                            Fat = 0m,
                            Fibre = 4m,
                            Name = "Broccoli",
                            Protein = 3m,
                            Salt = 0m,
                            Sugar = 2m
                        },
                        new
                        {
                            Id = 14,
                            Calories = 25m,
                            Carbohydrates = 3m,
                            Fat = 0m,
                            Fibre = 5m,
                            Name = "Brussels",
                            Protein = 3m,
                            Salt = 0m,
                            Sugar = 3m
                        },
                        new
                        {
                            Id = 15,
                            Calories = 375m,
                            Carbohydrates = 80m,
                            Fat = 1m,
                            Fibre = 2m,
                            Name = "Bulgur groats",
                            Protein = 10m,
                            Salt = 0m,
                            Sugar = 2m
                        },
                        new
                        {
                            Id = 16,
                            Calories = 735m,
                            Carbohydrates = 1m,
                            Fat = 83m,
                            Fibre = 0m,
                            Name = "Butter",
                            Protein = 1m,
                            Salt = 0m,
                            Sugar = 1m
                        },
                        new
                        {
                            Id = 17,
                            Calories = 27m,
                            Carbohydrates = 5m,
                            Fat = 0m,
                            Fibre = 3m,
                            Name = "Carrot",
                            Protein = 1m,
                            Salt = 0m,
                            Sugar = 4m
                        },
                        new
                        {
                            Id = 18,
                            Calories = 20m,
                            Carbohydrates = 2m,
                            Fat = 0m,
                            Fibre = 2m,
                            Name = "Califlower",
                            Protein = 2m,
                            Salt = 0m,
                            Sugar = 2m
                        },
                        new
                        {
                            Id = 19,
                            Calories = 157m,
                            Carbohydrates = 0m,
                            Fat = 4m,
                            Fibre = 0m,
                            Name = "Chicken breast",
                            Protein = 30m,
                            Salt = 0m,
                            Sugar = 0m
                        },
                        new
                        {
                            Id = 20,
                            Calories = 103m,
                            Carbohydrates = 0m,
                            Fat = 2m,
                            Fibre = 0m,
                            Name = "Chicken leg",
                            Protein = 21m,
                            Salt = 0m,
                            Sugar = 0m
                        },
                        new
                        {
                            Id = 21,
                            Calories = 354m,
                            Carbohydrates = 66m,
                            Fat = 4m,
                            Fibre = 9m,
                            Name = "Corn",
                            Protein = 9m,
                            Salt = 0m,
                            Sugar = 2m
                        },
                        new
                        {
                            Id = 22,
                            Calories = 225m,
                            Carbohydrates = 0m,
                            Fat = 17m,
                            Fibre = 0m,
                            Name = "Duck",
                            Protein = 18m,
                            Salt = 0m,
                            Sugar = 0m
                        },
                        new
                        {
                            Id = 23,
                            Calories = 235m,
                            Carbohydrates = 1m,
                            Fat = 20m,
                            Fibre = 0m,
                            Name = "Eggs",
                            Protein = 14m,
                            Salt = 0m,
                            Sugar = 0m
                        },
                        new
                        {
                            Id = 24,
                            Calories = 247m,
                            Carbohydrates = 18m,
                            Fat = 12m,
                            Fibre = 2m,
                            Name = "Fish sticks",
                            Protein = 15m,
                            Salt = 0m,
                            Sugar = 1m
                        },
                        new
                        {
                            Id = 25,
                            Calories = 307m,
                            Carbohydrates = 46m,
                            Fat = 11m,
                            Fibre = 3m,
                            Name = "French fries",
                            Protein = 6m,
                            Salt = 0m,
                            Sugar = 0m
                        },
                        new
                        {
                            Id = 26,
                            Calories = 57m,
                            Carbohydrates = 14m,
                            Fat = 0m,
                            Fibre = 1m,
                            Name = "Grapes",
                            Protein = 1m,
                            Salt = 0m,
                            Sugar = 13m
                        },
                        new
                        {
                            Id = 27,
                            Calories = 201m,
                            Carbohydrates = 1m,
                            Fat = 13m,
                            Fibre = 0m,
                            Name = "Ham",
                            Protein = 22m,
                            Salt = 0m,
                            Sugar = 1m
                        },
                        new
                        {
                            Id = 28,
                            Calories = 667m,
                            Carbohydrates = 11m,
                            Fat = 63m,
                            Fibre = 8m,
                            Name = "Hazelnut",
                            Protein = 14m,
                            Salt = 0m,
                            Sugar = 9m
                        },
                        new
                        {
                            Id = 29,
                            Calories = 308m,
                            Carbohydrates = 76m,
                            Fat = 0m,
                            Fibre = 0m,
                            Name = "Honey",
                            Protein = 0m,
                            Salt = 0m,
                            Sugar = 75m
                        },
                        new
                        {
                            Id = 30,
                            Calories = 247m,
                            Carbohydrates = 60m,
                            Fat = 0m,
                            Fibre = 2m,
                            Name = "Jam",
                            Protein = 0m,
                            Salt = 0m,
                            Sugar = 59m
                        },
                        new
                        {
                            Id = 31,
                            Calories = 116m,
                            Carbohydrates = 1m,
                            Fat = 5m,
                            Fibre = 0m,
                            Name = "Kidneys(pork)",
                            Protein = 17m,
                            Salt = 0m,
                            Sugar = 0m
                        },
                        new
                        {
                            Id = 32,
                            Calories = 48m,
                            Carbohydrates = 10m,
                            Fat = 0m,
                            Fibre = 1m,
                            Name = "Kiwi",
                            Protein = 1m,
                            Salt = 0m,
                            Sugar = 8m
                        },
                        new
                        {
                            Id = 33,
                            Calories = 11m,
                            Carbohydrates = 1m,
                            Fat = 0m,
                            Fibre = 1m,
                            Name = "Lettuce",
                            Protein = 1m,
                            Salt = 0m,
                            Sugar = 1m
                        },
                        new
                        {
                            Id = 34,
                            Calories = 132m,
                            Carbohydrates = 2m,
                            Fat = 4m,
                            Fibre = 0m,
                            Name = "Liver(pork)",
                            Protein = 22m,
                            Salt = 0m,
                            Sugar = 2m
                        },
                        new
                        {
                            Id = 35,
                            Calories = 741m,
                            Carbohydrates = 3m,
                            Fat = 82m,
                            Fibre = 0m,
                            Name = "Mayonese",
                            Protein = 2m,
                            Salt = 0m,
                            Sugar = 3m
                        },
                        new
                        {
                            Id = 36,
                            Calories = 62m,
                            Carbohydrates = 4m,
                            Fat = 3m,
                            Fibre = 0m,
                            Name = "Milk",
                            Protein = 4m,
                            Salt = 0m,
                            Sugar = 4m
                        },
                        new
                        {
                            Id = 37,
                            Calories = 359m,
                            Carbohydrates = 80m,
                            Fat = 1m,
                            Fibre = 0m,
                            Name = "Rice",
                            Protein = 8m,
                            Salt = 0m,
                            Sugar = 0m
                        });
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.ProductHazard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HazardId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HazardId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductHazards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HazardId = 1,
                            ProductId = 29
                        },
                        new
                        {
                            Id = 2,
                            HazardId = 1,
                            ProductId = 30
                        },
                        new
                        {
                            Id = 3,
                            HazardId = 2,
                            ProductId = 36
                        },
                        new
                        {
                            Id = 4,
                            HazardId = 3,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.Meal", b =>
                {
                    b.HasOne("FitAppReact.EntityFramework.Models.MealCategory", "MealCategory")
                        .WithMany("Meals")
                        .HasForeignKey("MealCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealCategory");
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.MealProduct", b =>
                {
                    b.HasOne("FitAppReact.EntityFramework.Models.Meal", "Meal")
                        .WithMany("MealProducts")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitAppReact.EntityFramework.Models.Product", "Product")
                        .WithMany("MealProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.MedicalConditionHazard", b =>
                {
                    b.HasOne("FitAppReact.EntityFramework.Models.Hazard", "Hazard")
                        .WithMany("MedicalConditionHazards")
                        .HasForeignKey("HazardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitAppReact.EntityFramework.Models.MedicalCondition", "MedicalCondition")
                        .WithMany("MedicalConditionHazards")
                        .HasForeignKey("MedicalConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hazard");

                    b.Navigation("MedicalCondition");
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.ProductHazard", b =>
                {
                    b.HasOne("FitAppReact.EntityFramework.Models.Hazard", "Hazard")
                        .WithMany()
                        .HasForeignKey("HazardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitAppReact.EntityFramework.Models.Product", "Product")
                        .WithMany("ProductHazards")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hazard");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.Hazard", b =>
                {
                    b.Navigation("MedicalConditionHazards");
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.Meal", b =>
                {
                    b.Navigation("MealProducts");
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.MealCategory", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.MedicalCondition", b =>
                {
                    b.Navigation("MedicalConditionHazards");
                });

            modelBuilder.Entity("FitAppReact.EntityFramework.Models.Product", b =>
                {
                    b.Navigation("MealProducts");

                    b.Navigation("ProductHazards");
                });
#pragma warning restore 612, 618
        }
    }
}
